[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://eloquent-hugle-a260c6.netlify.com/*"
  to = "https://charadb.tkesgar.com/:splat"
  status = 301
  force = true
